CREATE TABLE IF NOT EXISTS TASKSTATUS (
  ID VARCHAR(99) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR(99) NOT NULL,
  USER_ID VARCHAR(99) NOT NULL,
  CREATED_TIME DATE NOT NULL,
  STATUS	VARCHAR(99)
  PRIMARY KEY  (ID)
);

CREATE INDEX TASKSTATUS_CREATEDTIME_INDEX ON TASKSTATUS
(
	CREATED_TIME
);

